##############################################
# Filename: Makefile
# Author: MIDN Ian Coffey (m261194)
# Makefile for Proj02
##############################################

############### Make All #######################
all: Encryptor.java TestEncryptors.java Caesar.java Clear.java Vigenere.java ASCIIBoundsException.java Hasher.java TestHashers.java Padcut.java Shift.java Vault.java User.java FormatException.java AlgorithmException.java

	javac Encryptor.java
	javac TestEncryptors.java
	javac Caesar.java
	javac Clear.java
	javac Vigenere.java
	javac ASCIIBoundsException.java
	javac Hasher.java 
	javac TestHashers.java 
	javac Padcut.java
	javac Shift.java
	javac Vault.java
	javac User.java 
	javac FormatException.java
	javac AlgorithmException.java

############### Individual Make #######################
Encryptor: Encryptor.java
	javac Encryptor.java

TestEncryptors: TestEncryptors.java
	javac TestEncryptors.java

Caesar: Caesar.java
	javac Caesar.java

Clear: Clear.java
	javac Clear.java

Vigenere: Vigenere.java
	javac Vigenere.java

ASCIIBoundsException: ASCIIBoundsException.java
	javac ASCIIBoundsException.java

Hasher: Hasher.java
	javac Hasher.java 

TestHashers: TestHashers.java
	javac TestHashers.java 

Padcut: Padcut.java
	javac Padcut.java

Shift: Shift.java
	javac Shift.java

Vault: Vault.java
	javac Vault.java

User: User.java 
	javac User.java

FormatException: FormatException.java
	javac FormatException.java

AlgorithmException: AlgorithmException.java
	javac AlgorithmException.java









